// evolution-rules.js
// Generado a partir del orden de window.PokemonData (pokemon-data.js)
// Nota: por ahora solo Budew y Roselia tienen condiciones; el resto está marcado como no_evo.

const EvolutionRules = {
  "Budew>Roselia": { method: "level", level: 16 },
  "Roselia>Roserade": { method: "level", level: 35 },
  "Roserade": { no_evo: true },
  "Litwick>Lampent": { method: "level", level: 18 },
  "Lampent>Chandelure": { method: "level", level: 32 },
  "Chandelure": { no_evo: true },
  "Spheal>Sealeo": { method: "level", level: 14 },
  "Sealeo>Walrein": { method: "level", level: 39 },
  "Walrein": { no_evo: true },
  "Fresworm>Pomagoon": { method: "level", level: 16 },
  "Pomagoon>Fragalys": { method: "level", level: 30 },
  "Fragalys": { no_evo: true },
  "Lauchesta>K'waren": { method: "special", details: "Sube al nivel 20 teniendo a Nyakid en el equipo" },
  "K´Waren": { no_evo: true },
  "Rattata>Raticate": { method: "level", level: 20, time: "day" },
  "Raticate": { no_evo: true },
  "Charachon>Cucararmor": { method: "item", item: "Revestimiento Metálico" },
  "Cucararmor": { no_evo: true },
  "Seedot>Nuzleaf": { method: "level", level: 14 },
  "Nuzleaf>Shiftry": { method: "item", item: "Piedra Hoja" },
  "Nuzleaf>Sountry": { method: "special", details: "Hembra, de noche, luna llena y cerca de un cuerpo de agua" },
  "Shiftry": { no_evo: true },
  "Sountry": { no_evo: true },
  "Ferroseed>Ferrothorn": { method: "level", level: 40 },
  "Ferrothorn": { no_evo: true },
  "Nyakid>Nyaitle": { method: "special", details: "Sube al nivel 20 teniendo a Lauchesta en el equipo" },
  "Nyaitle": { no_evo: true },
  "Capynder>Thundabara": { method: "level", level: 40, weather: "rain" },
  "Thundabara": { no_evo: true },
  "Vacabal": { no_evo: true },
  "Zubat>Golbat": { method: "level", level: 22 },
  "Golbat>Crobat": { method: "friendship" },
  "Crobat": { no_evo: true },
  "Gorinfante>Babuigore": { method: "level", level: 33 },
  "Babuigore>Goreilla": { method: "level", level: 66, time: "night", location: "zona oscura" },
  "Goreilla": { no_evo: true },
  "Copocido>Nitrosquito": { method: "item_gender", item: "Piedra Hielo", gender: "female" },
  "Nitrosquito": { no_evo: true },
  "Surskit>Masquerain": { method: "level", level: 22 },
  "Masquerain": { no_evo: true },
  "Ekans>Arbok": { method: "move", move: "Mimic" },
  "Arbok": { no_evo: true },
  "Smoochum>Jynx": { method: "level", level: 30 },
  "Jynx": { no_evo: true },
  "Furrdupe": { no_evo: true },
  "Armifur": { no_evo: true },
  "Ditto": { no_evo: true },
  "Eevee>Vaporeon": { method: "item", item: "Piedra Agua" },
  "Eevee>Jolteon": { method: "item", item: "Piedra Trueno" },
  "Eevee>Flareon": { method: "item", item: "Piedra Fuego" },
  "Eevee>Espeon": { method: "friendship", time: "day" },
  "Eevee>Umbreon": { method: "friendship", time: "night" },
  "Eevee>Leafeon": { method: "location", location: "Roca Musgo" },
  "Eevee>Glaceon": { method: "location", location: "Roca Hielo" },
  "Eevee>Sylveon": { method: "friendship_move", moveType: "Fairy" },
  "Eevee>Echoveon": { method: "item", item: "Campana Óxido" },
  "Vaporeon": { no_evo: true },
  "Jolteon": { no_evo: true },
  "Flareon": { no_evo: true },
  "Espeon": { no_evo: true },
  "Umbreon": { no_evo: true },
  "Leafeon": { no_evo: true },
  "Glaceon": { no_evo: true },
  "Sylveon": { no_evo: true },
  "Echoveon": { no_evo: true },
  "Jigglypuff>Wigglytuff": { method: "item", item: "Piedra Luna" },
  "Wigglytuff": { no_evo: true },
  "Oddish>Gloom": { method: "level", level: 21 },
  "Gloom>Vileplume": { method: "item", item: "Piedra Hoja" },
  "Gloom>Bellossom": { method: "item", item: "Piedra Sol" },
  "Vileplume": { no_evo: true },
  "Bellossom": { no_evo: true },
  "Lotad>Lombre": { method: "level", level: 14 },
  "Lombre>Ludicolo": { method: "item", item: "Piedra Agua" },
  "Ludicolo": { no_evo: true },
  "Whismur>Loudred": { method: "level", level: 20 },
  "Loudred>Exploud": { method: "level", level: 40 },
  "Exploud": { no_evo: true },
  "Drampa": { no_evo: true },
  "Chingling>Chimecho": { method: "friendship", time: "night" },
  "Chimecho": { no_evo: true },
  "Pyroky>Pyroover": { method: "level", level: 23 },
  "Pyroover>Pyrotill": { method: "friendship", value: 0 },
  "Pyrotill": { no_evo: true },
  "Drumseth": { no_evo: true },
  "Gleebin": { no_evo: true },
  "Zigzagoon>Linoone": { method: "level", level: 20 },
  "Linoone>Rocktagoon": { method: "move", move: "Roca Afilada" },
  "Rocktagoon": { no_evo: true },
  "Kricketot>Kricketune": { method: "level", level: 10 },
  "Kricketune": { no_evo: true },
  "Mimikyu": { no_evo: true },
  "Buneary>Lopunny": { method: "friendship", time: "night" },
  "Lopunny": { no_evo: true },
  "Solosis>Duosion": { method: "level", level: 32 },
  "Duosion>Reuniclus": { method: "level", level: 41 },
  "Reuniclus": { no_evo: true },
  "Machop>Machoke": { method: "level", level: 28 },
  "Machoke>Machamp": { method: "trade" },
  "Machamp": { no_evo: true },
  "Gimmighoul>Gholdengo": { method: "special", details: "Reunir 999 monedas de Gimmighoul" },
  "Gholdengo": { no_evo: true },
  "Shuppet>Banette": { method: "level", level: 37 },
  "Banette": { no_evo: true },
  "Mudbray>Mudsdale": { method: "level", level: 30 },
  "Mudsdale": { no_evo: true },
  "Drilbur>Excadrill": { method: "level", level: 31 },
  "Excadrill": { no_evo: true },
  "Mareanie>Toxapex": { method: "level", level: 38 },
  "Toxapex": { no_evo: true },
  "Stufful>Bewear": { method: "level", level: 27 },
  "Bewear": { no_evo: true },
  "Llamerú": { no_evo: true },
  "Magikarp>Gyarados": { method: "level", level: 20 },
  "Gyarados": { no_evo: true },
  "Sentret>Furret": { method: "level", level: 15 },
  "Furret>Phurstep": { method: "special", details: "Caminar 10.000 pasos con Furret" },
  "Phurstep": { no_evo: true },
  "Rokrauco": { no_evo: true },
  "Lechonk>Oinkologne": { method: "level", level: 18, gender: "male" },
  "Lechonk>Oinkologne": { method: "level", level: 18, gender: "female" },
  "Oinkologne": { no_evo: true },
  "Tynamo>Eelektrik": { method: "level", level: 39 },
  "Eelektrik>Eelektross": { method: "item", item: "Piedra Trueno" },
  "Eelektross": { no_evo: true },
  "Zapixy": { no_evo: true },
  "Timburr>Gurdurr": { method: "level", level: 25 },
  "Gurdurr>Conkeldurr": { method: "trade" },
  "Conkeldurr": { no_evo: true },
  "Gible>Gabite": { method: "level", level: 24 },
  "Gabite>Garchomp": { method: "level", level: 48 },
  "Garchomp": { no_evo: true },
  "Slowpoke>Slowbro": { method: "trade_item", item: "Roca del Rey" },
  "Slowpoke>Slowking": { method: "item", item: "Roca del Rey" },
  "Slowbro": { no_evo: true },
  "Slowking": { no_evo: true },
  "Italroof": { no_evo: true },
  "Larvitar>Pupitar": { method: "level", level: 30 },
  "Pupitar>Tyranitar": { method: "level", level: 55 },
  "Tyranitar": { no_evo: true },
  "Venipede>Whirlipede": { method: "level", level: 22 },
  "Whirlipede>Scolipede": { method: "level", level: 30 },
  "Scolipede": { no_evo: true },
  "Zangoose": { no_evo: true },
  "Seviper": { no_evo: true },
  "Trengkai": { no_evo: true },
  "Porygon>Porygon2": { method: "trade_item", item: "Mejora" },
  "Porygon2>Porygon-Z": { method: "trade_item", item: "Disco Extraño" },
  "Porygon3": { no_evo: true },
  "Porygon-Z>Porygon3": { method: "item", item: "Antivirus" },
  "Porygon-Z>Nulldata": { method: "special", details: "Al usar Antivirus, si hay espacio en el equipo y Poké Balls disponibles" },
  "Nulldata": { no_evo: true },
  "Clawrpion": { no_evo: true },
  "Okarópodo>Clarinopodo": { method: "item", item: "Piedra Alba" },
  "Clarinopodo": { no_evo: true },
  "Rotom": { no_evo: true },
  "Kichoing>Troncoing": { method: "level", level: 20 },
  "Troncoing": { no_evo: true },
  "Unlukat": { no_evo: true },
  "Pichu>Pikachu": { method: "friendship" },
  "Pikachu>Raichu": { method: "item", item: "Piedra Trueno" },
  "Raichu": { no_evo: true },
  "Crowdin": { no_evo: true },
  "Mjölhorn": { no_evo: true },
  "Salmóloki": { no_evo: true },
  "Jorminium>Jormarog": { method: "level", level: 59 },
  "Jormarog": { no_evo: true },
  "Ragnadog": { no_evo: true },
  "Lactasma>Cheespectro": { method: "special", details: "Dar giros como Alcremie durante clima soleado" },
  "Cheespectro": { no_evo: true },
  "Phantump>Trevenant": { method: "trade" },
  "Trevenant": { no_evo: true },
  "Wynaut>Wobbuffet": { method: "level", level: 15, move: "Salpicadura" },
  "Wobbuffet": { no_evo: true },
  "Spritzee>Aromatisse": { method: "trade_item", item: "Sachet" },
  "Aromatisse>Mediromitsse": { method: "trade_item", item: "Vidaesfera" },
  "Mediromitsse": { no_evo: true },
  "Natu>Xatu": { method: "level", level: 25 },
  "Xatu>Zatu": { method: "level", level: 50 },
  "Zatu": { no_evo: true },
  "Calidra>Calerna": { method: "level", level: 30 },
  "Calerna": { no_evo: true },
  "Yanma>Yanmega": { method: "move", move: "Poder Pasado" },
  "Yanmega": { no_evo: true },
  "Noibat>Noivern": { method: "level", level: 48 },
  "Noivern": { no_evo: true },
  "Frigibax>Arctibax": { method: "level", level: 35 },
  "Arctibax>Baxcalibur": { method: "level", level: 54 },
  "Baxcalibur": { no_evo: true },
  "Ponyta>Rapidash": { method: "level", level: 40 },
  "Rapidash": { no_evo: true },
  "Tauros": { no_evo: true },
  "Shuckle>Ghoushell": { method: "special", trigger: "ohko_defeat", resolves_at: "pokemon_center" },
  "Ghoushell": { no_evo: true },
  "Olimantwist>Vagantyss": { method: "move", move: "Juego Sucio" },
  "Vagantyss": { no_evo: true },
  "Glowtopus>Octocry": { method: "level", level: 30 },
  "Octocry>Octorture": { method: "trade_item", item: "Llamasfera" },
  "Octorture": { no_evo: true },
  "Cocroak>Froconut": { method: "level", level: 16 },
  "Froconut>Ribboxer": { method: "level", level: 40 },
  "Ribboxer": { no_evo: true },
  "Répio>Cuccollo": { method: "level", level: 16 },
  "Cuccollo>Kirilloki": { method: "level", level: 36 },
  "Kirilloki": { no_evo: true },
  "Ghoulpin>Zombakuda": { method: "move", move: "Triturar" },
  "Zombakuda": { no_evo: true },
  "Atawana": { no_evo: true },
  "Toxel>Toxtricity": { method: "level", level: 30, variant: "nature" },
  "Toxtricity": { no_evo: true },
  "Minccino>Cinccino": { method: "item", item: "Piedra Día" },
  "Cinccino": { no_evo: true },
  "Nosepass>Probopass": { method: "location", location: "Campo Magnético" },
  "Probopass": { no_evo: true },
  "Dinamonky>Primanoro": { method: "level", level: 30 },
  "Primanoro": { no_evo: true },
  "Chinchou>Lanturn": { method: "level", level: 27 },
  "Lanturn>Aqualume": { method: "item", item: "Piedra Trueno" },
  "Aqualume": { no_evo: true },
  "Gligar>Gliscor": { method: "level_hold", item: "Colmillo Agudo", time: "night" },
  "Gliscor": { no_evo: true },
  "Condorimno": { no_evo: true },
  "Riolu>Lucario": { method: "friendship", time: "day" },
  "Lucario": { no_evo: true },
  "Patriemul": { no_evo: true },
  "Bonsly>Sudowoodo": { method: "move", move: "Mimic" },
  "Sudowoodo>Woodoliat": { method: "move", move: "Poder Pasado" },
  "Woodoliat": { no_evo: true },
  "Aron>Lairon": { method: "level", level: 32 },
  "Lairon>Aggron": { method: "level", level: 42 },
  "Aggron": { no_evo: true },
  "Elgyem>Beheeyem": { method: "level", level: 42 },
  "Beheeyem>Mixyem": { method: "level", level: 64 },
  "Mixyem": { no_evo: true },
  "Slakoth>Vigoroth": { method: "level", level: 18 },
  "Vigoroth>Slaking": { method: "level", level: 36 },
  "Vigoroth>Releking": { method: "level_hold", level: 36, item: "Insignia Regia" },
  "Slaking": { no_evo: true },
  "Resleking": { no_evo: true },
  "Narvedge": { no_evo: true },
  "Belulu>Burbelu": { method: "friendship" },
  "Belulu>Belugangel": { method: "item", item: "Piedra Día" },
  "Belugangel": { no_evo: true },
  "Birboxer": { no_evo: true },
  "Voldonkey": { no_evo: true },
  "Chi Huan Fu": { no_evo: true },
  "Imperako": { no_evo: true },
  "Topystar": { no_evo: true },
  "Caphumo": { no_evo: true },
  "Axolosaur": { no_evo: true },
  "Maskingu": { no_evo: true },
  "Platby>Plateen": { method: "level", level: 16 },
  "Plateen>Platerain": { method: "level", level: 30 },
  "Plateen>Pollitypus": { method: "level_hold", level: 30, item: "Flecha Venenosa" },
  "Pollitypus": { no_evo: true },
  "Platerain": { no_evo: true },
  "Delibird>Bonaclaus": { method: "friendship", item: "Saco de Tela" },
  "Delibird>Doompus": { method: "special", details: "Sosteniendo Saco de Tela y usando Piedra Noche" },
  "Bonaclaus": { no_evo: true },
  "Doompus": { no_evo: true },
  "Dürfenant>Durant": { method: "friendship" },
  "Dürfenant>Scharfant": { method: "level_hold", item: "Roca del Rey" },
  "Scharfant": { no_evo: true },
  "Heater>Heatmor": { method: "friendship" },
  "Heater>Heatmotor": { method: "item", item: "Piedra Fuego" },
  "Heatmotor": { no_evo: true },
  "Muulukka": { no_evo: true },
  "Kecleon>Mimikleon": { method: "level_hold", item: "Escama Dragón" },
  "Mimikleon": { no_evo: true },
  "Snover>Abomasnow": { method: "level", level: 40 },
  "Abomasnow": { no_evo: true },
  "Bullning>Bullayer": { method: "level", level: 66 },
  "Bullayer": { no_evo: true },
  "Tinkatink>Tinkatuff": { method: "level", level: 24 },
  "Tinkatuff>Tinkaton": { method: "level", level: 38 },
  "Tinkaton": { no_evo: true },
  "Capsakid>Scovillain": { method: "item", item: "Piedra Fuego" },
  "Scovillain>Scozilla": { method: "move", move: "Poder Pasado" },
  "Scozilla": { no_evo: true },
  "Shroodle>Grafaiai": { method: "level", level: 28 },
  "Grafaiai>Graffistree": { method: "move", move: "Polución" },
  "Graffistree": { no_evo: true },
  "Yamask>Polybrigus": { method: "trade_item", item: "Mejora", alternative: "Cordon Unión" },
  "Polybrigus": { no_evo: true },
  "Beldum>Metang": {  method: "level", level: 20 },
  "Metang>Metagross": { method: "level", level: 45 },
  "Metagross": { no_evo: true },
  "Relicanth": { no_evo: true },
  "Phancorch>Esperift": { method: "level_hold", item: "Cuerda Gruesa", time: "night" },
  "Esperift": { no_evo: true },
  "Regirest": { no_evo: true },
  "Regigneo": { no_evo: true },
  "Regitube": { no_evo: true },
  "Mewtwo": { no_evo: true },
  "Aligolver": { no_evo: true },
  "Alifeat": { no_evo: true },
  "Trevus": { no_evo: true },
  "Innybit": { no_evo: true },
  "Centurala": { no_evo: true },
  "Pincomarina": { no_evo: true },
  "Meloetta": { no_evo: true },
};

if (typeof window !== 'undefined') window.EvolutionRules = EvolutionRules;
